import { Routes } from '@angular/router';
import { LoginComponent }     from './pages/auth/login/login';
import { RegisterComponent }  from './pages/auth/register/register';
import { HomeComponent }      from './pages/home/home';
import { DashboardComponent } from './pages/dashboard/dashboard';
import { BookingsComponent }  from './pages/bookings/bookings';
import { CarsComponent }      from './pages/cars/cars';
import { PaymentsComponent }  from './pages/payments/payments';
import { ReviewsComponent }   from './pages/reviews/reviews';
import { ServicesComponent }  from './pages/services/services';
import { ProfileComponent }   from './pages/profile/profile';
import { AdminComponent }     from './pages/admin/admin';
import { WasherComponent }    from './pages/washer/washer';

export const routes: Routes = [
  { path: '',          component: HomeComponent },
  { path: 'home',      component: HomeComponent },
  { path: 'login',     component: LoginComponent },
  { path: 'register',  component: RegisterComponent },
  { path: 'dashboard', component: DashboardComponent },
  { path: 'bookings',  component: BookingsComponent },
  { path: 'cars',      component: CarsComponent },
  { path: 'payments',  component: PaymentsComponent },
  { path: 'reviews',   component: ReviewsComponent },
  { path: 'services',  component: ServicesComponent },
  { path: 'profile',   component: ProfileComponent },
  { path: 'admin',     component: AdminComponent },
  { path: 'washer',    component: WasherComponent },
];
